default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: salesapp_dev

test:
  <<: *default
  database: salesapp_test

production:
  <<: *default
  database: salesapp_prod
  user: rails
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>
