# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

[
  "Ericsson",
  "Vattenfall",
  "Skanska",
  "Volvo Cars",
  "H&M",
  "TeliaSonera",
  "Electrolux",
  "Preem",
  "Sandvik AB",
  "ICA Gruppen",
  "Stora Enso",
  "Atlas Copco",
  "Nordea",
  "SCA",
  "Scania",
  "Securitas",
  "Nordstjernan AB",
  "SKF",
  "ABB",
  "Axel Johnson",
  "NCC",
  "Astrazeneca",
  "Sony Mobile Communications",
  "Peab",
  "Assa Abloy",
  "Tele2",
  "E.ON",
  "Boliden",
  "SSAB",
  "Postnord",
  "If Skadeförsäkring",
  "SEB",
  "St1",
  "Kooperativa Förbundet (KF)",
  "Autoliv",
  "Swedbank",
  "Axfood",
  "Lantmännen",
  "Scandinavian Airlines",
  "Stena Metall",
  "Folksamgruppen",
  "Handelsbanken",
  "Statoil",
  "Husqvarna",
  "Alfa Laval",
  "Bonnierkoncernen",
  "LKAB",
  "Stena",
  "Ratos",
  "Länsförsäkringsgruppen",
  "Alecta",
  "Nynas",
  "Systembolaget",
  "SAAB",
  "Getinge",
  "Investor",
  "Fortum Sweden",
  "Toyota",
  "OKQ8",
  "Trelleborg",
  "L E Lundbergföretagen",
  "Apoteket",
  "Hexagon",
  "Cellmark"
  "Ahlsell AB",
  "Volkswagen",
  "IKEA",
  "Holmen",
  "Bilia",
  "Tetra Pak",
  "AMF",
  "Aarhuskarlshamn",
  "Södra Skogsägarna",
  "Skandia",
  "Arla Foods",
  "Akzo Nobel",
  "Storstockholms Lokaltrafik",
  "Papyrus",
  "Samsung Electronics",
  "Modern Times Group (MTG)",
  "Pfizer",
  "Meda",
  "Aktiebolaget Trav och Galopp(ATG)",
  "Swedish Match",
  "Schenker",
  "JM",
  "Telenor",
  "Nobia",
  "Ekman & Co",
  "TD Tech Data",
  "Martin & Servera",
  "Loomis",
  "Outokumpu Stainless",
  "Gambro",
  "Hewlett-Packard",
  "Bergendahl & Son",
  "Fritidsresor",
  "Perstorp",
  "BillerudKorsnäs"].each do |title|
  Org.create title: title, org_num: rand(10000000..99999999)
end

['Mat & dryck', 'Kontorsmaterial', 'Transport', 'IT'].each do |cat|
  SpecCategory.create(title: cat)
end

